map_path: "$(find top_down_render)/maps/west_point"
live_map: False
estimate_scale: False
use_raster: False
svg_res: 2.946
svg_origin_x: 0
svg_origin_y: 0
init_pos_px_x: 600
init_pos_px_y: 809
init_pos_px_cov: 20
